### ISSUE TITLE
Debug translation keys error 

### ISSUE THREAD

**Issue by iamibadd** [simplelocalize/simplelocalize-cli#102]
**Describe the bug**

I'm downloading the translation keys from but seeing the below error. 

`
Established active environments: [cli]
Loading configuration file from: simplelocalize.yml
Configuration file loaded successfully
Preparing files to download
Request failed: We couldn't produce a valid nested JSON file(s) due to the current state of translation keys naming. Translation key cannot contain nesting and translation text on the same level.
Command failed. Use '--debug' parameter before the command name to see stacktrace.
`

How do I know what keys and namespaces are affected?

**CLI Version**

2.2.0

**Operating system (please complete the following information):**
 - OS: Mac OS
 - OS Version: 14.4.1 x86_64
 - CPU Architecture: M2

**Screenshots**

<img width="1245" alt="image" src="https://github.com/simplelocalize/simplelocalize-cli/assets/33521605/b1711c2f-13cd-4a06-b73c-ba97d2e30306">

**Comment by jpomykala** [comment]
Hey @iamibadd 

Thank you for reporting the issue. Could you please re-execute the export command? The CLI should now display the full message along with the problematic keys

**Comment by iamibadd** [comment]
Awsome! It worked and is a life saver. 

Thank you!
