### ISSUE TITLE
Accept intl.formatMessage syntax in React Apps

### ISSUE THREAD

**Issue by mwq27** [simplelocalize/simplelocalize-cli#11]
When using intl.formatMessage, the CLI only looks for 
```js
intl.formatMessage(defineMessages({...})
```
However, this seems to be not recommended by the react-intl team https://formatjs.io/docs/getting-started/message-declaration.

Can we have the recommended format supported? 
```js
intl.formatMessage({ id: 'KEY', defaultMessage: '...'})
```

**Comment by jpomykala** [comment]
@mwq27 Thanks for the support. Your changes are live in version 0.3.0 👍 
https://github.com/simplelocalize/simplelocalize-cli/releases/tag/0.3.0
