### ISSUE TITLE
Java and Spring Support

### ISSUE THREAD

**Issue by mykong89** [simplelocalize/simplelocalize-cli#22]
Can we adjust somehow this CLI to support Spring Framework and grab message.properties files?

**Comment by jpomykala** [comment]
Hey! Yes, we are thinking about extracting keys and available translation from message_XX.properties. On roadmap we are also thinking about providing special Java/Spring service for fetching translations from CDN using MessageSource Spring components :)

**Comment by jpomykala** [comment]
Will be implemented in https://github.com/simplelocalize/simplelocalize-cli/pull/31
