### ISSUE TITLE
CLI bug? <FormattedHTMLMessage id=""/>

### ISSUE THREAD

**Issue by bob-hrebenciuc** [simplelocalize/simplelocalize-cli#25]
I think I found the bug in CLI. I'm using the latest version (2020-10-16 11:45) with `projectType: yahoo/react-intl` CLI is putting `<FormattedHTMLMessage id="add-credits-title` instead just a key.

![Screenshot 2020-10-16 at 11 44 05](https://user-images.githubusercontent.com/72972254/96243335-e7074a80-0fa4-11eb-8489-877bc3a1b6fe.png)

![Screenshot 2020-10-16 at 11 42 53](https://user-images.githubusercontent.com/72972254/96243242-baebc980-0fa4-11eb-809c-eeed432bfa9e.png)

```
<div className="header-content">
              <h1>
                <FormattedHTMLMessage id="header-text"/>
              </h1>
              <h3>
                <FormattedHTMLMessage id="header-subtitle"/>
              </h3>
              <LinkTranslated to="/offer" className="btn btn-primary btn-cta">
                <FormattedMessage id="header-button"/>
              </LinkTranslated>
</div>
```

**Comment by jpomykala** [comment]
Weird bug, I checked your example and looks fine. What kind of encoding do you use?
