### ISSUE TITLE
Import JSON keys and values through Rest Endpoint

### ISSUE THREAD

**Issue by marques-p44** [simplelocalize/simplelocalize-cli#6]
### Feature Request:

I'm very happy that we can upload keys and values in an Excel sheet through a Rest endpoint now. I would love it if we could also pass a JSON object, so that we're not tied to Microsoft Excel.

**Comment by pelirroja** [comment]
Done in another repository. Docs: https://docs.simplelocalize.io/api/create-translations
Feel free to re-open if something more will be needed.
