### ISSUE TITLE
iOS stringsdict (Pluralisation) support

### ISSUE THREAD

**Issue by apps4everyone** [simplelocalize/simplelocalize-cli#80]
Hey, was looking into the fileFormats documentation and was missing any hint about Pluralisation support. 
(maybe only missing in the documentation)

Is it possible to download e.g. iOS .stringsdict files?

Thank you Stefan
PS: if not is there any timeline?

**Comment by apps4everyone** [comment]
Hey @jpomykala, sorry for disturbing but maybe you can point me quickly to the right direction in documentation. Thx

**Comment by jpomykala** [comment]
Hey @apps4everyone !

At the moment, there is no option to export translations into .stringsdict files. I will take a look what should be done to provide a support for it in the following days.

I’m closing this issue as it’s not directly connected with the CLI. Feel free to contact me via email (jakub@simplelocalize.io) in case of any additional questions. ☺️

Thanks,
Jakub

**Comment by apps4everyone** [comment]
Hey, @jpomykala,
thx for the Info. Pluralisation is unfortunately a blocker for me, without support your nice tool has to be skipped from the evaluation of new tools.

Cheers Stefan
If you have questions: email stefan@apps4everyone.at
